language: python
python:
  # Python versions encountered in the wild (AKA in Open Knesset)
  - "2.7.3"
  - "2.7.9"
  # Python version on latest Ubuntu - used by developers
  # also, datapackage is made only for this version (in .travis/script.sh)
  - "2.7.12"
addons:
  apt:
    packages:
    - antiword
    - language-pack-he
install:
  - .travis/install.sh
script:
  - .travis/script.sh
after_script:
  - pkill -9 -f "sshproxy" || true
